# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows run the workflow manually

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Build Environment
      run: |
        sw_vers
        xcode-select -p
        xcodebuild -version
        xcrun simctl list devices

    - name: Build
      run: make build
    - name: Run Tests
      run: make test
